-- Inserting 510 VAPE CARTRIDGES data
INSERT INTO public.vaporizer (class, name, type, quantity, strength, price) VALUES 
('Indica', 'Back Forty | Kush Mint Cart', 'CARTRIDGE', '1g', '90.0', '$36.99'),
('Hybrid', 'Booty | Peppermint OG Cart', 'CARTRIDGE', '1g', '83.9', '$36.99'),
('Sativa', 'Booty | Tangie Cart', 'CARTRIDGE', '1g', '84.6', '$36.99'),
('Sativa', 'BOLD | Cherry Bomb Cart', 'CARTRIDGE', '1g', '88.5', '$36.99'),
('Indica', 'BOLD | Tiger''s Blood Cart', 'CARTRIDGE', '1g', '88.5', '$36.99'),
('Indica', 'Endgame | Platinum Punch Cart', 'CARTRIDGE', '1g', '93', '$36.99'),
('Indica', 'FIGR | Maple Kush Cart', 'CARTRIDGE', '1g', '80.2', '$36.99'),
('Sativa', 'FIGR | Pineapple Express Cart', 'CARTRIDGE', '1g', '80.6', '$36.99'),
('Sativa', 'FIGR | Purple Trainwreck Cart', 'CARTRIDGE', '1g', '80.6', '$36.99'),
('Hybrid', 'Good Supply | Blue Dream Cart', 'CARTRIDGE', '1g', '88.6', '$36.99'),
('Sativa', 'Good Supply | Pineapple Express Cart', 'CARTRIDGE', '1g', '91.0', '$36.99'),
('Hybrid', 'Good Supply | Purple Monkey Cart', 'CARTRIDGE', '1g', '92.0', '$36.99'),
('Sativa', 'Ness | Apricot Jelly Cart', 'CARTRIDGE', '1g', '90.3', '$36.99'),
('Indica', 'Ness | Ninja Fruit Cart', 'CARTRIDGE', '1g', '90.3', '$36.99'),
('Indica', 'Ritual Gold | Black Mamba Cart', 'CARTRIDGE', '1g', '83.4', '$36.99'),
('Indica', 'Spinach | Atomic Sour Grapefruit Cart', 'CARTRIDGE', '1g', '82.5', '$36.99'),
('Sativa', 'Spinach | Pineapple Paradise Cart', 'CARTRIDGE', '1g', '91.2', '$36.99'),
('Indica', 'Tweed | Mango Haze Cart', 'CARTRIDGE', '1g', '85.0', '$36.99'),
('Sativa', 'ShredX | Tropic Thunder Cart', 'CARTRIDGE', '1g', '88.0', '$36.99'),
('Sativa', 'Tweed | Lemonberry Cart', 'CARTRIDGE', '1g', '85.0', '$36.99'),
('Indica', 'WeedMe | Wedding Cart', 'CARTRIDGE', '1g', '83.6', '$36.99'),
('Sativa', '♥ Spinach | Pink Lemonade Cart', 'CARTRIDGE', '1.2g', '83.3', '$39.99'),
('Indica', 'Roilty | Catacomb Kush Shatter Cart', 'CARTRIDGE', '1g', '89.5', '$39.99'),
('Indica', 'RAD | Rainbow Kush Live Resin Cart', 'CARTRIDGE', '1g', '78.5', '$41.99'),
('Hybrid', 'Seaweed | MAX Green Rocks Cart', 'CARTRIDGE', '1g','58.7', '$44.99'),
('Indica', 'Seaweed | MAX ZaZa Cart', 'CARTRIDGE', '1g', '58.4', '$44.99'),
('Indica', 'BOXHOT | Cherry Kush Cart', 'CARTRIDGE', '1g', '83.3', '$45.51'),
('Sativa', 'BOXHOT | Peach OG Cart', 'CARTRIDGE', '1.2g', '83.3', '$45.51'),
('Hybrid', 'BOXHOT | Alien OG Cart', 'CARTRIDGE', '1.2g', '83.3', '$45.51'),
('Hybrid', 'Greybeard | KISH Live Resin Cart', 'CARTRIDGE', '1g', '74.0', '$45.99'),
('Sativa', 'Greybeard | Slymer Live Resin Cart', 'CARTRIDGE', '1g', '72.6', '$45.99'),
('Sativa', 'BOXHOT | Nitro Cart', 'CARTRIDGE', '2g', '50.0 THC / 25.0 CBG', '$54.99');

-- Inserting DISPOSABLE VAPES data
INSERT INTO public.vaporizer (class, name, type, quantity, strength, price) 
VALUES 
('Indica', 'Shred X | Blueberry Blaster Disposable', 'DISPOSABLE', '0.3g', '88.0', '$24.99'),
('Indica', 'Lord Jones | Dead Head OG', 'DISPOSABLE', '0.5g', '74.0', '$31.99'),
('Sativa', 'Lord Jones | Purple Lemon Haze', 'DISPOSABLE', '0.5g', '75.0', '$31.99'),
('Sativa', 'Higgs | Live Resin Disposable', 'DISPOSABLE', '0.5g', '77.1', '$32.99'),
('Hybrid', 'Sherbinskis | Orange Sherbs Live Resin', 'DISPOSABLE', '0.5g', '70.0', '$34.99'),
('Indica', 'Sherbinskis | Pink Sherbs Live Resin', 'DISPOSABLE', '0.5g', '75.4', '$34.99'),
('Indica', 'Tweed | Mango Haze Disposable', 'DISPOSABLE', '1g', '85.0', '$42.98'),
('Hybrid', 'BOXHOT | Alien OG Disposable', 'DISPOSABLE', '1g', '85.0', '$42.99'),
('Sativa', 'BOXHOT | Peach OG Disposable', 'DISPOSABLE', '1g', '82.2', '$42.99');
